# Generated by Django 5.2.17 on 2026-10-03 08:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(default='India (national grid)', max_length=80)),
                ('kg_co2_per_kwh', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='factor (kg CO2/kWh)')),
                ('kind', models.CharField(choices=[('static', 'Static published factor'), ('modelled', 'Model-derived (Phase 12 random forest)')], default='static', max_length=16)),
                ('source', models.TextField(help_text='Provenance. Returned with every CO2 figure.')),
                ('is_verified', models.BooleanField(default=False, help_text='False means the value has not been checked against a primary source.')),
                ('is_default', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('fixed_charge_inr_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged regardless of consumption.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='fixed charge (INR/month)')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Applied to the energy charge plus fixed charge.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_sample', models.BooleanField(default=True, help_text='True for illustrative rates. The UI must label these as samples.')),
                ('source', models.TextField(blank=True, help_text='Where these rates came from. Shown alongside every estimate.')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used when a request does not name a tariff.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, help_text='Leave empty for a shared sample tariff available to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='spaces.organisation')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='spaces.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.emissionfactor')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.tariff')),
            ],
            options={
                'verbose_name_plural': 'billing settings',
            },
        ),
        migrations.CreateModel(
            name='TimeOfUseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_hour', models.PositiveSmallIntegerField(help_text='Local hour, 0-23, inclusive.')),
                ('end_hour', models.PositiveSmallIntegerField(help_text='Local hour, 1-24, exclusive.')),
                ('multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='1.0 is no change; 1.2 is a 20% peak surcharge; 0.9 a 10% rebate.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tou_rates', to='billing.tariff')),
            ],
            options={
                'ordering': ['tariff', 'start_hour'],
            },
        ),
        migrations.CreateModel(
            name='TariffSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_kwh', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='from (kWh/month)')),
                ('to_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for the final, unbounded block.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='to (kWh/month)')),
                ('rate_inr_per_kwh', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='rate (INR/kWh)')),
                ('label', models.CharField(blank=True, max_length=60)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='billing.tariff')),
            ],
            options={
                'ordering': ['tariff', 'from_kwh'],
                'constraints': [models.UniqueConstraint(fields=('tariff', 'from_kwh'), name='unique_slab_start_per_tariff')],
            },
        ),
    ]
