"""
Raw data sources and their provenance.

Two sources feed the models:

1. **UCI "Individual household electric power consumption"** - real measured data
   from one household near Paris, 1-minute sampling, December 2006 to November
   2010. One download attempt is made; if it fails the pipeline falls back to the
   synthetic generator and **labels every output as synthetic**, per the plan's
   fallback rule.

2. **Synthetic grid emission factor rows** - there is no public hourly CO2
   intensity series for the Indian grid that this project can download, so the
   Phase 12 random forest trains on a generated series whose *shape* is plausible
   (coal-heavy baseload overnight, solar dilution at midday, peaking plants in
   the evening). It is **not measured data** and is never presented as such.

Provenance is written to a JSON sidecar next to every processed file, so a
downstream model or document can state where its numbers came from rather than
assuming they are real.

**Units in the UCI data, which are a trap this project cares about:**

* `Global_active_power`   - **kilowatts** (instantaneous), not kWh
* `Global_reactive_power` - kilovolt-amperes reactive
* `Voltage`               - volts
* `Global_intensity`      - amperes
* `Sub_metering_1/2/3`    - **watt-hours** of active energy per minute

So the active power column and the sub-metering columns are in different unit
families. `clean.py` converts both into one explicit kWh-per-interval column and
names it accordingly.
"""

from __future__ import annotations

import io
import json
import urllib.error
import urllib.request
import zipfile
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path

#: Root of the ml package, so paths work regardless of the caller's cwd.
ML_DIR = Path(__file__).resolve().parent.parent
RAW_DIR = ML_DIR / "data" / "raw"
PROCESSED_DIR = ML_DIR / "data" / "processed"
ARTIFACTS_DIR = ML_DIR / "artifacts"

#: UCI archive URL. Tried exactly once - never retried in a loop (plan rule 5).
UCI_URL = (
    "https://archive.ics.uci.edu/static/public/235/"
    "individual+household+electric+power+consumption.zip"
)
UCI_MEMBER = "household_power_consumption.txt"
UCI_LOCAL = RAW_DIR / UCI_MEMBER

#: Seconds before the single download attempt is abandoned.
DOWNLOAD_TIMEOUT = 60


@dataclass
class Provenance:
    """Where a dataset came from. Serialised beside every processed file."""

    dataset: str
    is_synthetic: bool
    source: str
    licence: str = ""
    units: dict[str, str] = field(default_factory=dict)
    rows: int | None = None
    first_timestamp: str | None = None
    last_timestamp: str | None = None
    notes: list[str] = field(default_factory=list)
    generated_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat(timespec="seconds")
    )

    def as_dict(self) -> dict:
        return asdict(self)

    def write(self, path: Path) -> Path:
        """Write the sidecar as `<path>.provenance.json`."""
        target = path.with_suffix(path.suffix + ".provenance.json")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(self.as_dict(), indent=2), encoding="utf-8")
        return target


UCI_PROVENANCE = Provenance(
    dataset="UCI Individual household electric power consumption",
    is_synthetic=False,
    source=(
        "UCI Machine Learning Repository, dataset 235 "
        "(archive.ics.uci.edu/dataset/235). Measurements from a single household "
        "in Sceaux, near Paris, at 1-minute resolution, December 2006 to "
        "November 2010."
    ),
    licence="Creative Commons Attribution 4.0 International (CC BY 4.0)",
    units={
        "Global_active_power": "kW (instantaneous active power)",
        "Global_reactive_power": "kVAr",
        "Voltage": "V",
        "Global_intensity": "A",
        "Sub_metering_1": "Wh per minute (kitchen)",
        "Sub_metering_2": "Wh per minute (laundry)",
        "Sub_metering_3": "Wh per minute (water heater and AC)",
    },
    notes=[
        "Missing values are encoded as '?' in the source file.",
        "One household in France: its load shape is not representative of an "
        "Indian home or office. Used because it is a long, real, freely "
        "licensed series for forecasting, not as a local baseline.",
    ],
)

SYNTHETIC_LOAD_PROVENANCE = Provenance(
    dataset="Synthetic household load",
    is_synthetic=True,
    source=(
        "Generated by ml/data/synthetic.py. Used when the UCI download is "
        "unavailable, per the project plan's fallback rule."
    ),
    units={"energy_kwh": "kWh per interval", "mean_power_w": "W"},
    notes=[
        "SYNTHETIC - not measured consumption. Any metric computed from this "
        "data must be labelled synthetic wherever it is reported.",
    ],
)

SYNTHETIC_EMISSION_PROVENANCE = Provenance(
    dataset="Synthetic grid emission factor",
    is_synthetic=True,
    source=(
        "Generated by ml/data/synthetic.py. No downloadable hourly CO2 intensity "
        "series for the Indian grid is used by this project, so the Phase 12 "
        "random forest trains on a generated series."
    ),
    units={
        "kg_co2_per_kwh": "kg CO2 per kWh",
        "load_mw": "MW (national demand proxy)",
    },
    notes=[
        "SYNTHETIC - the shape is plausible (coal baseload overnight, solar "
        "dilution at midday, peaking plants in the evening) but the values are "
        "not measurements of any real grid.",
        "A model trained on this learns the generator's assumptions, not the "
        "grid. Phase 12 metrics must say so.",
    ],
)


class DownloadUnavailable(RuntimeError):
    """The single download attempt failed. Callers fall back to synthetic data."""


def download_uci(force: bool = False) -> Path:
    """
    Fetch the UCI archive, **once**.

    Returns the path to the extracted text file. Raises `DownloadUnavailable`
    rather than retrying, so the caller can fall back immediately. A file already
    on disk is reused unless `force` is set.
    """
    if UCI_LOCAL.exists() and not force:
        return UCI_LOCAL

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    try:
        request = urllib.request.Request(
            UCI_URL, headers={"User-Agent": "EcoTrack/0.1 (research project)"}
        )
        with urllib.request.urlopen(request, timeout=DOWNLOAD_TIMEOUT) as response:
            payload = response.read()
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, OSError) as error:
        raise DownloadUnavailable(f"Could not download the UCI dataset: {error}") from error

    try:
        with zipfile.ZipFile(io.BytesIO(payload)) as archive:
            names = archive.namelist()
            member = UCI_MEMBER if UCI_MEMBER in names else next(
                (name for name in names if name.endswith(".txt")), None
            )
            if member is None:
                raise DownloadUnavailable(
                    f"The UCI archive contained no .txt member; found {names}."
                )
            UCI_LOCAL.write_bytes(archive.read(member))
    except zipfile.BadZipFile as error:
        raise DownloadUnavailable(
            f"The UCI download was not a valid zip archive: {error}"
        ) from error

    return UCI_LOCAL


def uci_available() -> bool:
    """True when the raw file is already on disk, with no network access."""
    return UCI_LOCAL.exists()
