# Generated by Django 5.2.17 on 2026-10-03 07:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in square metres. Leave empty to derive it from children.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='area (m2)')),
                ('occupancy', models.PositiveIntegerField(blank=True, help_text='Typical number of people. Leave empty to derive it from children.', null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['organisation__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in square metres. Leave empty to derive it from children.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='area (m2)')),
                ('occupancy', models.PositiveIntegerField(blank=True, help_text='Typical number of people. Leave empty to derive it from children.', null=True)),
                ('level', models.IntegerField(default=0, help_text='0 is ground level; negatives are basements.')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='spaces.building')),
            ],
            options={
                'ordering': ['building__name', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organisation__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='organisations', through='spaces.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spaces.organisation'),
        ),
        migrations.AddField(
            model_name='building',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='spaces.organisation'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in square metres. Leave empty to derive it from children.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='area (m2)')),
                ('occupancy', models.PositiveIntegerField(blank=True, help_text='Typical number of people. Leave empty to derive it from children.', null=True)),
                ('kind', models.CharField(choices=[('office', 'Office'), ('meeting', 'Meeting room'), ('kitchen', 'Kitchen'), ('server', 'Server room'), ('bedroom', 'Bedroom'), ('living', 'Living room'), ('other', 'Other')], default='other', max_length=16)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='spaces.floor')),
            ],
            options={
                'ordering': ['floor__building__name', 'floor__level', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'level'), name='unique_floor_level_per_building'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_membership_per_org'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_building_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'name'), name='unique_room_name_per_floor'),
        ),
    ]
