# Generated by Django 5.2.17 on 2026-10-03 10:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('home_energy', 'Home energy'), ('diet', 'Diet'), ('shopping', 'Shopping'), ('waste', 'Waste')], max_length=16)),
                ('key', models.SlugField(help_text="Stable identifier, e.g. 'car-petrol'.", max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('quantity_unit', models.CharField(help_text='Unit the quantity is measured in: km, kWh, meals, items, kg.', max_length=20)),
                ('kg_co2_per_unit', models.DecimalField(decimal_places=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source', models.TextField(help_text='Where the factor came from. Shown with every figure.')),
                ('is_verified', models.BooleanField(default=False, help_text='False means the value has not been checked against a primary source.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_co2_per_month', models.DecimalField(decimal_places=2, help_text='Target kilograms of CO2e per month across all categories.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='co2_budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('kg_co2', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=12)),
                ('factor_snapshot', models.DecimalField(decimal_places=5, default=Decimal('0'), editable=False, help_text='The factor used at entry time, so a later correction cannot rewrite history.', max_digits=10)),
                ('is_verified', models.BooleanField(default=False, editable=False, help_text='Manual entries are self-reported, so always False. Only telemetry-backed reductions are verified (Phase 21).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_entries', to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='activity.emissionfactorrow')),
            ],
            options={
                'verbose_name_plural': 'activity entries',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['user', '-occurred_on'], name='activity_user_date_idx')],
            },
        ),
    ]
