# Generated by Django 5.2.17 on 2026-10-03 07:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('mains', 'Whole-space mains meter'), ('appliance', 'Single appliance meter'), ('simulated', 'Simulator')], default='mains', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive devices are refused at ingestion.')),
                ('sample_interval_seconds', models.PositiveIntegerField(default=30, help_text='How often the device is expected to post. Drives the online check.', validators=[django.core.validators.MinValueValidator(1)])),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, help_text='First characters of the token, to identify it in the UI.', max_length=8)),
                ('token_issued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last successful request from this device.', null=True)),
                ('last_reading_at', models.DateTimeField(blank=True, help_text='Timestamp of the newest reading stored, which may predate last_seen_at.', null=True)),
                ('reported_buffer_count', models.PositiveIntegerField(blank=True, help_text="Readings still queued in the device's flash, as the device reports them.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='spaces.room')),
            ],
            options={
                'ordering': ['room__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the sample was taken on the device.')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the server stored it.')),
                ('voltage_v', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('500'))], verbose_name='voltage (V)')),
                ('current_a', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('200'))], verbose_name='current (A)')),
                ('power_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('active_power_w', models.DecimalField(decimal_places=2, help_text='Instantaneous real power in watts.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='active power (W)')),
                ('energy_wh', models.DecimalField(decimal_places=4, help_text='Energy for this interval only, never a cumulative meter total.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='energy this interval (Wh)')),
                ('source', models.CharField(choices=[('device', 'Device'), ('simulator', 'Simulator'), ('import', 'Manual import')], default='device', max_length=16)),
                ('was_buffered', models.BooleanField(default=False, help_text='Arrived well after its timestamp, i.e. replayed from the device buffer.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_device_name_per_room'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['device', 'timestamp'], name='reading_device_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('device', 'timestamp'), name='unique_reading_per_device_timestamp'),
        ),
    ]
