# Generated by Django 5.2.17 on 2026-10-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.CharField(choices=[('isolation_forest', 'Isolation Forest'), ('seasonal_zscore', 'Seasonal baseline z-score'), ('rule_night_load', 'Rule: load during unoccupied night hours'), ('rule_baseload_jump', 'Rule: baseload step change'), ('rule_device_left_on', 'Rule: device left running')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('observed_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('expected_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='What the seasonal baseline expected. Null when the detector has no baseline.', max_digits=12, null=True)),
                ('excess_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('score', models.FloatField(blank=True, help_text='Detector score: z-score, or Isolation Forest decision function.', null=True)),
                ('title', models.CharField(max_length=160)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed as not a problem')], default='open', max_length=16)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_anomalies', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='telemetry.device')),
            ],
            options={
                'verbose_name_plural': 'anomalies',
                'ordering': ['-window_start', '-severity'],
                'indexes': [models.Index(fields=['state', '-window_start'], name='anomaly_state_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'detector', 'window_start'), name='unique_anomaly_per_device_detector_window')],
            },
        ),
    ]
