# Generated by Django 5.2.17 on 2026-10-03 11:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('building_count', models.PositiveIntegerField(default=0)),
                ('total_kwh', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('total_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kwh_per_sqm', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_kwh'],
            },
        ),
        migrations.CreateModel(
            name='CityNo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=9)),
                ('no2_umol_per_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tropospheric NO2 column (umol/m2)')),
                ('population_millions', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observed_on', models.DateField(blank=True, null=True)),
                ('source', models.TextField(help_text='Provenance. Returned with every value.')),
                ('is_measured', models.BooleanField(default=False, help_text='False for the static fallback values seeded without Earth Engine.')),
                ('anomaly_score', models.FloatField(blank=True, help_text='Isolation Forest decision function.', null=True)),
                ('is_hotspot', models.BooleanField(default=False)),
                ('hotspot_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'city NO2 reading',
                'verbose_name_plural': 'city NO2 readings',
                'ordering': ['-no2_umol_per_m2'],
                'constraints': [models.UniqueConstraint(fields=('city', 'state'), name='unique_city_state')],
            },
        ),
    ]
