# Generated by Django 5.2.17 on 2026-10-03 10:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('threshold_verified_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('threshold_streak_days', models.PositiveIntegerField(blank=True, null=True)),
                ('threshold_verified_claims', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['threshold_verified_kwh', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('target_kwh', models.DecimalField(decimal_places=2, help_text='Verified kWh a participant must save to complete it.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reward_xp', models.PositiveIntegerField(default=100)),
                ('reward_coins', models.PositiveIntegerField(default=50)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_xp', models.PositiveIntegerField(default=0, help_text='Earned only from telemetry-confirmed savings.')),
                ('verified_kwh_saved', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('eco_coins', models.PositiveIntegerField(default=0)),
                ('unverified_xp', models.PositiveIntegerField(default=0, help_text='From self-reported activity. Never counted in the leaderboard, because it is not evidence.')),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_active_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_xp'],
            },
        ),
        migrations.CreateModel(
            name='SavingClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(help_text="What was changed, e.g. 'raised AC setpoint to 26 C'.", max_length=200)),
                ('baseline_start', models.DateTimeField()),
                ('baseline_end', models.DateTimeField()),
                ('claim_start', models.DateTimeField()),
                ('claim_end', models.DateTimeField()),
                ('claimed_kwh_saved', models.DecimalField(decimal_places=4, help_text='What the user believes was saved.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('baseline_kwh', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('claim_period_kwh', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('measured_kwh_saved', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='baseline_kwh - claim_period_kwh, after length normalisation.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Confirmed by telemetry'), ('rejected', 'Not supported by telemetry'), ('unverifiable', 'Not enough telemetry to check')], default='pending', max_length=16)),
                ('verification_note', models.TextField(blank=True, editable=False)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_claims', to='telemetry.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_kwh_saved', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_participation_per_challenge')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='unique_badge_per_user')],
            },
        ),
    ]
